language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

script:
  - docker-compose up -d
  - cd eyes.selenium.java/
  - mvn test
  - docker-compose down
